[package]
name = "rstun"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stun = "0.4.1"
clap = "2.34.0"
num_cpus= "1.13.0"
nix = "0.23.0"